### ISSUE TITLE
Execute all these scripts to get data & fix the bugs which comes after execution to successfully executed.

### ISSUE THREAD

**Issue by saurTarento** [saurTarento/analytics#21]
INSERT INTO tbl_users (fullName, email, password, status) 
VALUES ('John Doe', 'john.doe@example.com', 'secure123', 1);
INSERT INTO tbl_users (fullName, email, password, status) 
VALUES ('Jane Smith', 'jane.smith@example.com', 'password456', 1);
 INSERT INTO tbl_users (fullName, email, password, status) 
VALUES ('Jane Smith', 'jane.smith@example.com', 'password456', 1);
 INSERT INTO tbl_users (fullName, email, password, status) 
VALUES ('Inactive User', 'inactive.user@example.com', 'password999', 0);
 INSERT INTO tbl_courses (title, header, description, status, created, createdByUserId) 
VALUES 
('Data Science with SQL', 'Data Science', 'Use SQL for data analysis', 1, NOW(), 3),
('SQL Performance Tuning', 'Advanced', 'Optimize SQL queries for large datasets', 1, NOW(), 4);
INSERT INTO tbl_courses (title, header, description, status, created, updated, createdByUserId) 
VALUES ('Database Administration', 'Admin', 'Learn to manage and administer databases', 1, NOW(), NULL, 5);
INSERT INTO tbl_courses (title, header, description, status, created, createdByUserId) 
VALUES ('Deprecated SQL Techniques', 'Old', 'Outdated SQL techniques for legacy systems', 0, NOW(), 2);
INSERT INTO tbl_courses (title, header, description, status, created, createdByUserId) 
VALUES 
('Data Science with SQL', 'Data Science', 'Use SQL for data analysis', 1, NOW(), 3),
('SQL Performance Tuning', 'Advanced', 'Optimize SQL queries for large datasets', 1, NOW(), 4);

**Comment by subhamNodeDev** [comment]
https://prnt.sc/Gv7motZbzQiV

https://prnt.sc/ME1PZEZu2Wuh

This is done now.

**Comment by saurTarento** [comment]
Verified
